config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "books/show", to: "books#show"
  get "books/find", to: "books#find"
  get "books/search", to: "books#search"
  get "books/searchlike", to: "books#searchlike"
  get "sessions/new"
  get "users/new"
  resources :activities
  resources :books do
    resources :reviews do
      resources :comments
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    member do
      get :following, :followers
    end
  end
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :suggests

  namespace :admin do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#index"
    resources :books, except: :show
    resources :categories, except: [:edit, :show]
    resources :users
    resources :suggests
  end
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid without_default_scope: true
  has_many :books, dependent: :destroy

  validates :name, presence: true

  scope :sort_by_name, ->{order :name}
  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  layout "admin"
  authorize_resource
  before_action :find_category, only: %i(update destroy)

  def index
    @search_categories = Category.ransack params[:q]
    @categories = @search_categories.result.sort_by_name.paginate page: params[:page],
     per_page: 10
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "controller.category.create_category"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def update
    @category = Category.restore(params[:id], recursive: true)
    if @category
      flash[:success] = t "controller.category.restore_category"
    else
      flash[:danger] = t "controller.category.nofound"
    end
    redirect_to admin_categories_path
  end

  def destroy
    if @category.destroy
      flash[:success] = t "controller.category.temporary_category"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "un_delete"
      redirect_to admin_root_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :parent_id
  end

  def find_category
    @category = Category.find_by_id params[:id]
    return if @category
    flash[:danger] = t "fail"
    redirect_to admin_root_path
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
  def load_categories
    Category.sort_by_name
  end
end

app/views/admin/categories/_category.html.erb
<tr class="gradeX">
  <td id="catId"><%= category.id %></td>
  <td>
    <label for="rad1">
      <%= link_to category.name, books_path(category: category.id), class: "link" %>
    </label>
  </td>
  <td class="center">
    <% unless category.deleted_at %>
      <%= link_to t("admin.categories.delete_category"), admin_category_path(category), method: :delete, data:{confirm: t("sure")}, class: "btn btn-danger " %>
    <% else %>
      <%= link_to t("admin.categories.restore_category"), admin_category_path(category), method: :patch, class: "btn btn-success " %>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_search_categories.html.erb
<%= search_form_for @search_categories, url: admin_categories_path, method: :get do |f| %>
  <div class="field">
    <%= f.text_field :name_cont, class: "form-control",
      placeholder: t("view.admin.category.search_category") %>
    <%= f.submit t("view.admin.submit_search"), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
  <div>
    <h2><%= t ("admin.static_pages.index.category") %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-responsive">
          <div class="row">
            <%= render "search_categories" %>
            <div class="col-sm-6">
              <a href="/admin/categories/new" class="btn btn-success btn-md"><%= t "admin.categories.add_category" %></a>
            </div>
          </div>
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th><%= t "admin.categories.id" %></th>
                <th><%= t "admin.categories.category_name" %></th>
                <th class="action"><%= t "admin.categories.action" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "category", collection: load_categories, as: :category %>
            </tbody>
          </table>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/categories/new.html.erb
<div>
  <div id="page-inner">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t "admin.categories.add" %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="form-group">
              <label><%= t ".name" %></label>
              <%= simple_form_for [:admin, @category], html: {multipart: true} do |f| %>
                <%= f.label :parent_id %>
                <%= f.text_field :parent_id %>
                <%= f.label :Category_name %>
                <%= f.text_field :name %>
                <%= f.submit t("admin.categories.add_category"), class: "btn btn-success btn-md" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>