config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "books/show", to: "books#show"
  get "books/find", to: "books#find"
  get "books/search", to: "books#search"
  get "books/searchlike", to: "books#searchlike"
  get "sessions/new"
  get "users/new"
  resources :activities
  resources :books do
    resources :reviews do
      resources :comments
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    member do
      get :following, :followers
    end
  end
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :suggests

  namespace :admin do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#index"
    resources :books, except: :show
    resources :categories, except: [:edit, :show]
    resources :users
    resources :suggests
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :books
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :activities, dependent: :destroy
  # has_many :marks, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
   foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
   foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :name, presence: true, length:
    {maximum: Settings.user.name.max_length}
  scope :sort_by_name, ->{order :name}
  scope :activated, ->{where activated: true}
  scope :sort_by_created_at, ->{order created_at: :DESC}
  mount_uploader :picture, PictureUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :validatable, :omniauthable
  enum role: {user: 0, admin: 1}

  def follow other_user
    following << other_user
  end

  # Unfollows a user.
  def unfollow other_user
    following.delete other_user
  end

  # Returns true if the current user is following the other user.
  def following? other_user
    following.include? other_user
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[6, 15]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  layout "admin"
  authorize_resource
  before_action :load_user, only: %i(update destroy)

  def index
    @search = User.ransack params[:q]
    @users = @search.result.sort_by_created_at.paginate page: params[:page],
      per_page: Settings.controllers.user.index_page_admin
    @users_all = User.sort_by_created_at.all
    respond_to do |format|
      format.html
      format.csv {send_data @users_all.to_csv}
      format.xls {send_data @users_all.to_csv(col_sep: "\t")}
    end
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to admin_users_path
      flash[:success] = t "controller.user.create_user"
    else
      render :new
    end
  end

  def update
    @user.role = @user.admin? ? User.roles[:user] : User.roles[:admin]
    if @user.save
      respond_to do |format|
        format.html{ redirect_to request.referrer }
        format.js
      end
    else
      flash[:danger] = t "controller.user.nofound"
      redirect_to request.referrer
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controller.user.delete_user"
      redirect_to admin_users_path
    else
      flash[:danger] = t "controller.user.delete_faild"
      redirect_to admin_root_path
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :phone,
      :address, :password, :password_confirmation, :role, :picture
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "controller.user.find_user_error"
    redirect_to admin_root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :load_user, except: :index
  before_action :load_follow, :load_unfollow, only: %i(following followers show)

  def index
    @users = User.sort_by_name.paginate page: params[:page],
      per_page: Settings.controllers.user.index_page
    respond_to do |format|
      format.html
      format.csv {send_data @users.to_csv}
      format.xls {send_data @users.to_csv(col_sep: "\t")}
    end
  end

  def show; end

  def following
    @title = t "controller.user.following"
    @users = @user.following.paginate page: params[:page],
      per_page: Settings.per_page
    render :show_follow
  end

  def followers
    @title = t "controller.user.followers"
    @users = @user.followers.paginate page: params[:page],
      per_page: Settings.per_page
    render :show_follow
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :phone,
      :address, :password, :password_confirmation, :role, :picture
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "controller.user.find_user_error"
    redirect_to root_path
  end

  # def correct_user
  #   redirect_to root_path unless current_user?(@user)
  # end

  # def admin_user
  #   redirect_to root_path unless current_user.admin?
  # end

  def load_follow
    @follow = current_user.active_relationships.build
  end

  def load_unfollow
    @unfollow = current_user.active_relationships.find_by(followed_id: @user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.helpers.user.size
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/_search_user.html.erb
<%= search_form_for @search, url: admin_users_path, method: :get do |f| %>
  <div class="field">
    <%= f.label :name_cont, t("admin.users.search_user") %>
    <%= f.text_field :name_cont, class: "form-control",
      placeholder: t("view.admin.user.search_user") %>
    <%= f.text_field :email_cont, class: "form-control",
      placeholder: t("view.admin.user.search_email") %>
    <%= f.select :role_cont, options_for_select(User.roles),
    prompt: t("view.admin.user.selection_role") %>
    <%= f.submit t("view.admin.submit_search"), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="update_<%= user.id %>" >
  <table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
      <tr>
        <th class="id"><%= t("admin.users.id") %></th>
        <th class="name"><%= t("admin.users.user_name") %></th>
        <th class="email"><%= t("admin.users.email") %></th>
        <th class="role"><%= t("admin.users.role") %></th>
        <th class="action"><%= t "admin.users.action" %></th>
      </tr>
    </thead>
    <tbody>
      <tr class=" gradeX">
        <td id="catId"><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
          <% if user.admin? %>
            <td><span class="label label-info"><%= user.role %></span></td>
          <% else %>
            <td><span class="label label-default"><%= user.role %></span></td>
          <% end %>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to t("admin.users.delete"), admin_user_path(user), method: :delete,
              data: { confirm: t("view.users.user.sure") },class: "fa fa-trash btn btn-danger " %>
            <%= link_to user.admin? ? t("admin.users.setuser") : t("admin.users.setadmin"), admin_user_path(user), method: :patch, class: "btn btn-success", remote: true %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/users/index.html.erb
  <div>
    <h2><%= t "admin.users.user" %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-responsive">
        <div class="row"></div>
        <%= render "search_user" %>
        <div class="add-user"><%= link_to t("admin.users.add_user"), new_admin_user_path, class: "btn btn-success" %></div>
        <div class="export">
            <i><%= t("view.users.index.download") %></i>
            <%= link_to t("view.users.index.users_xls"), admin_users_path(format: Settings.export.xls), class: "fa fa-check btn btn-success " %>
            <%= link_to t("view.users.index.users_csv"), admin_users_path(format: Settings.export.csv), class: "fa fa-check btn btn-success " %>
        </div>
        <%= render @users %>
        <%= will_paginate @users %>
        <%= pie_chart User.group(:name).count,
          title: t("statistics_user"),download: "review_book", library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 1}}} %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/users/new.html.erb
<h2><%= t ".add_user" %></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for [:admin, @user] do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.select :role, options_for_select(select_roles) %>
        <%= f.file_field :picture %>
        <%= f.input :name, required: true, autofocus: true %>
        <%= f.input :email, required: true, autofocus: true %>
        <%= f.input :address, required: true, autofocus: true %>
        <%= f.input :password,required: true,
          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), input_html: { autocomplete: t(".new-password") } %>
        <%= f.input :password_confirmation, required: true,
          input_html: { autocomplete: t(".new-password") } %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, t("view.admin.user.sign_up"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, current_user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <% if current_user.image %>
          <%= image_tag(current_user.image)%>
        <% else %>
          <%= image_tag current_user.picture.url if current_user.picture? %>
        <% end %>
        <%= current_user.name %>
      </h3>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-4">
    <p><b>Tên:</b> <i><%= current_user.name %></i></p>
    <p><b>Địa chỉ email:</b> <i><%= current_user.email %></i></p>
    <% if current_user.address %>
      <p><b>Địa chỉ:</b> <i><%= current_user.address %></i></p>
    <% end %>
    <p><b>Quyền:</b> <i><%= current_user.role %></i></p>
    <p><b>Trạng thái: </b><span aria-label="Đang hoạt động" style="background: rgb(66, 183, 42);border-radius: 50%;display: inline-block;height: 10px;width: 10px;"></span> Online</p>
  </div>
</div>

app/views/admin/users/update.js.erb
$('#update_<%= @user.id %>').html('<%= j render @user %> ');