config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "books/show", to: "books#show"
  get "books/find", to: "books#find"
  get "books/search", to: "books#search"
  get "books/searchlike", to: "books#searchlike"
  get "sessions/new"
  get "users/new"
  resources :activities
  resources :books do
    resources :reviews do
      resources :comments
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    member do
      get :following, :followers
    end
  end
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :suggests

  namespace :admin do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#index"
    resources :books, except: :show
    resources :categories, except: [:edit, :show]
    resources :users
    resources :suggests
  end
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  include PublicActivity::Common
  belongs_to :user

  validates :title, presence: true
  scope :newest, ->{order created_at: :desc}
  enum status: [:waiting, :rejected, :accepted]

  delegate :name, to: :user, prefix: true, allow_nil: true

  scope :by_suggest, ->(user_id){where user_id: user_id if user_id.present?}
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  layout "admin"
  before_action :load_suggest, :build_book, except: :index

  def index
    @suggests = Suggest.newest.paginate page:
      params[:page], per_page: Settings.per_page
  end

  def update
    @suggest.status = params[:value]
    if @suggest.save
      flash[:success] = t "controller.suggests.rejected"
    else
      flash[:danger] = t "controller.suggests.fail"
    end
    redirect_to admin_suggests_path
  end

  def edit; end

  private

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return @suggest
    flash[:danger] = t "controller.suggests.loadsuggest"
    redirect_to admin_root_path
  end

  def build_book
    @book = Book.new
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  before_action :require_log_in
  before_action :load_suggest, only: :destroy
  before_action :suggest_by_user, only: :index
  authorize_resource

  def index; end

  def new
    @suggest = current_user.suggests.build
  end

  def create
    @suggest = Suggest.new suggest_params
    if @suggest.save
      @suggest.create_activity :create, owner: current_user
      SendEmailJob.set(wait: 10.seconds).perform_later(@suggest)
      flash[:success] = t "suggests.create.success_rq"
      redirect_to suggests_path(user_id: current_user)
    else
      flash.now[:danger] = t "can't_rq"
      render :new
    end
  end

  def destroy
    if @suggest.destroy
      flash[:success] = t "suggests.create.delete_suggest"
      redirect_to suggests_path(user_id: current_user)
    else
      flash[:danger] = t "un_delete"
      redirect_to root_path
    end
  end

  private

  def suggest_params
    params.require(:suggest).permit :user_id, :title, :content, :author,
      :categories
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return if @suggest
    flash[:danger] = t "controller.no_data_rq"
    redirect_to root_path
  end

  def suggest_by_user
    @suggests = current_user.suggests.newest.by_suggest params[:user_id]
  end
end

app/views/admin/suggests/_suggest.html.erb
<tr class=" gradeX">
  <td id="catId"><%= suggest.id %></td>
  <td><%= suggest.title %></td>
  <td><%= suggest.categories %></td>
  <td><%= suggest.user_name %></td>
  <% if suggest.waiting? %>
    <td><span class="label label-warning"><%= suggest.status %></span></td>
  <% elsif suggest.accepted? %>
    <td><span class="label label-success"><%= suggest.status %></span></td>
  <% else %>
    <td><span class="label label-danger"><%= suggest.status %></span></td>
  <% end %>
  <td class="center">
    <% if suggest.waiting? %>
      <%= link_to t("view.suggests.index.accept"), edit_admin_suggest_path(suggest), method: :get, class: "fa fa-user btn btn-success " %>
      <%= link_to t("view.suggests.index.reject") , admin_suggest_path(suggest, value: :rejected), method: :put, class: "fa fa-trash btn btn-danger " %>
    <% end %>
  </td>
</tr>

app/views/admin/suggests/edit.html.erb
<% provide :button_text, t("admin.books.form.submit_add") %>
<div>
  <div id="page-inner">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t ".add_book" %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-">
          <div class="panel-body">
            <div class="form-group">
              <%= simple_form_for [:admin, @book], html: {multipart: true} do |f| %>
              <div>
                <%= f.select :category_id, options_for_select(load_categories_for_selectbox),
                 prompt: "select a category" %>
                <%= link_to "add category", new_admin_category_path %>
              </div>
                <%= f.hidden_field :suggest_id,value: @suggest.id %>
                <%= f.file_field :book_img %>
                <%= f.input :title, input_html: { value: @suggest.title }%>
                <%= f.input :description, as: :ckeditor %>
                <%= f.input :content, as: :ckeditor %>
                <%= f.input :author, input_html: { value: @suggest.author } %>
                <%= f.input :publisher %>
                <%= f.input :rate_points %>
                <%= f.input :number_pages %>
                <%= f.submit yield(:button_text), class: "btn btn-success btn-md" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/suggests/index.html.erb
  <div>
    <h2><%= t "admin.suggests.suggest" %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-responsive">
        <div class="row"></div>
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th class="id"><%= t "admin.suggests.id" %></th>
              <th class="name"><%= t "admin.suggests.name_book" %></th>
              <th class="category"><%= t "admin.suggests.name_category" %></th>
              <th class="username"><%= t "admin.suggests.user_name" %></th>
              <th class="status"><%= t "admin.suggests.status" %></th>
              <th class="action-suggests"><%= t "admin.suggests.action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @suggests %>
          </tbody>
        </table>
          <%= will_paginate @suggests %>
        <% if Suggest.any? %>
          <%= pie_chart Suggest.joins(:user).group(:name).count,
            title: t("statistics_user"),download: "review_book", library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 1}}} %>
          <%= pie_chart Suggest.joins(:user).group(:status).count,
            title: t("statistics_status"),download: "review_book", library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 1}}} %>
        <% end %>
        </div>
      </div>
    </div>
  </div>